// <auto-generated />
using System;
using Kontokorrent.Impl.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kontokorrent.Migrations
{
    [DbContext(typeof(KontokorrentContext))]
    [Migration("20200712012445_Private")]
    partial class Private
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("Kontokorrent.Impl.EF.BenutzerKontokorrent", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BenutzerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KontokorrentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KontokorrentId");

                    b.ToTable("BenutzerKontokorrent");
                });

            modelBuilder.Entity("Kontokorrent.Impl.EF.BenutzerSecret", b =>
                {
                    b.Property<string>("BenutzerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedSecret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BenutzerId");

                    b.ToTable("BenutzerSecret");
                });

            modelBuilder.Entity("Kontokorrent.Impl.EF.Bezahlung", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BearbeitetAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("TEXT");

                    b.Property<string>("BezahlendePersonId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KontokorrentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Wert")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Zeitpunkt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BezahlendePersonId");

                    b.HasIndex("KontokorrentId");

                    b.ToTable("Bezahlung");
                });

            modelBuilder.Entity("Kontokorrent.Impl.EF.EinladungsCode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GueltigBis")
                        .HasColumnType("TEXT");

                    b.Property<string>("KontokorrentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KontokorrentId");

                    b.ToTable("EinladungsCode");
                });

            modelBuilder.Entity("Kontokorrent.Impl.EF.EmfpaengerInBezahlung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BezahlungId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpfaengerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BezahlungId");

                    b.HasIndex("EmpfaengerId");

                    b.ToTable("EmfpaengerInBezahlung");
                });

            modelBuilder.Entity("Kontokorrent.Impl.EF.Kontokorrent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("OeffentlicherName")
                        .HasColumnName("Secret")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OeffentlicherName")
                        .IsUnique();

                    b.ToTable("Kontokorrent");
                });

            modelBuilder.Entity("Kontokorrent.Impl.EF.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("KontokorrentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasAlternateKey("KontokorrentId", "Name");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Kontokorrent.Impl.EF.BenutzerKontokorrent", b =>
                {
                    b.HasOne("Kontokorrent.Impl.EF.Kontokorrent", "Kontokorrent")
                        .WithMany("Benutzer")
                        .HasForeignKey("KontokorrentId");
                });

            modelBuilder.Entity("Kontokorrent.Impl.EF.Bezahlung", b =>
                {
                    b.HasOne("Kontokorrent.Impl.EF.Person", "BezahlendePerson")
                        .WithMany("Bezahlungen")
                        .HasForeignKey("BezahlendePersonId");

                    b.HasOne("Kontokorrent.Impl.EF.Kontokorrent", "Kontokorrent")
                        .WithMany("Bezahlungen")
                        .HasForeignKey("KontokorrentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kontokorrent.Impl.EF.EinladungsCode", b =>
                {
                    b.HasOne("Kontokorrent.Impl.EF.Kontokorrent", "Kontokorrent")
                        .WithMany("EinladungsCodes")
                        .HasForeignKey("KontokorrentId");
                });

            modelBuilder.Entity("Kontokorrent.Impl.EF.EmfpaengerInBezahlung", b =>
                {
                    b.HasOne("Kontokorrent.Impl.EF.Bezahlung", "Bezahlung")
                        .WithMany("Emfpaenger")
                        .HasForeignKey("BezahlungId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Kontokorrent.Impl.EF.Person", "Empfaenger")
                        .WithMany("EmfpaengerIn")
                        .HasForeignKey("EmpfaengerId");
                });

            modelBuilder.Entity("Kontokorrent.Impl.EF.Person", b =>
                {
                    b.HasOne("Kontokorrent.Impl.EF.Kontokorrent", "Kontokorrent")
                        .WithMany("Personen")
                        .HasForeignKey("KontokorrentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
